name: Build CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  UUID: copyous@boerdereinar.dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: ./.github/actions/setup

      - name: Lint
        run: make lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: ./.github/actions/setup
        with:
          install-gnome-extensions-tool: 'true'

      - name: Build
        run: RELEASE=1 make build

      - name: Prepare Artifact
        run: unzip dist/${{ env.UUID }}.zip -d dist/${{ env.UUID }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UUID }}
          path: dist/${{ env.UUID }}/*

  localization:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Gettext
        run: |
          sudo apt update
          sudo apt install -y gettext

      - name: Update POT
        run: |
          OLD_POT=$(grep -v '^"POT-Creation-Date":' resources/po/main.pot)
          make pot
          if diff -q -I '^"POT-Creation-Date": .*' <(echo "$OLD_POT") resources/po/main.pot; then
            echo "POT_CHANGED=false" >> $GITHUB_ENV
          else
            echo "POT_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Update PO
        if: env.POT_CHANGED == 'true'
        run: make po

      - uses: stefanzweifel/git-auto-commit-action@v7
        if: env.POT_CHANGED == 'true'
        with:
          commit_message: 'Update localization'
          file_pattern: 'resources/po'
